q1= input ("Hello there! Welcome to Mad Libs! Press P to begin or Q to quit. ")
if q1 == ('q'):
    quit
if q1 == ('p'):
    q2= print ('Select a topic:')
    q3= print ('1. Greetings, Earthlings!')
    q4= print ('2. Be Kind')
    q4= print ('3. How To Wash Your Face')
    q32= print ('4. Abducted by Aliens')
    q44= print ('5. Popular Video Game')
    q61= print ('6. Old Macdonald')
    q66= print ('7. Drgons')
    q77= print ('8. The WallMart Difference ')
    q93= print ('9. There Was An Old Woman')
    q99= print ('10. The Three Blind Mice')
    q5= input ('Just write the number of the topic you want to play. ')
while q5 == '1':
    q6= input ('NOUN (PLURAL) ')
    q7= input ('OCCUPATION ')
    q8= input ('ANIMAL (PLURAL) ')
    q9= input ('PLACE ')
    q10= input ('VERB ')
    q11= input ('NOUN ')
    print ('In the book War of the ' + (q6) + ', the main character is an anonymous ' + (q7) + ' who records the arrival of ' + (q8) + ' in ' + (q9) + '. Needless to say, havoc reigns as the ' + (q8) + ' continue to ' + (q10) + ' everything in sight, until they are killed by the common ' + (q11) + '.')
while q5 == '2':
    q12= input ("NOUN ")
    q13= input ("NOUN (PLURAL) ")
    q14= input ("NOUN ")
    q15= input ("PLACE ")
    q16= input ("ADJECTIVE ")
    q17= input ("NOUN ")
    print (f'Be kind to your {q12}-footed {q13} For a duck may be somebody`s {q14}, Be kind to your {q14} in {q15} Where the weather is always {q16}. You may think that this is the {q17}, Well it is.')
while q5== '3':
    q18= input ('ADVERB	')
    q19= input ('NOUN ')
    q20= input ('LIQUID ')
    q21= input ('VERB ')
    q22= input ('NUMBER	')
    q23= input ('NOUN (PLURAL) ')
    q24= input ('VERB ')
    q25= input ('ADJECTIVE ')
    q26= input ('NOUN ')
    q27= input ('NOUN (PLURAL) ')
    q28= input ('ILLNESS ')
    q29= input ('OCCUPATION ')
    q30= input ('BODY PART (PLURAL) ')
    q31= input ('BODY PART ')
    print (f'In order to wash your face {q18}, you must wet your {q19} in warm {q20}. Then, {q21} it across your face {q22} times. This will wash off any remainig {q23}. When you are done you should {q24} the cloth in {q25} water to clean it. You should also wash your face with a {q26} to keep it smooth and shiny. This will keep also keep away {q27}. Don`t worry. It is normal to experience {q28} the first time you try this. Consult your {q29} if you break out in {q30}. This works well on your {q31} too!')
while q5== '4':
    q33= input ('VERB ENDING IN "ING" ')
    q34= input ('VERB ENDING IN "ED" ')
    q35= input ('VERB ENDING IN "ED" ')
    q36= input ('NOUN ')
    q37= input ('VERB ')
    q38= input ('ANIMAL ')
    q39= input ('NOUN ')
    q40= input ('NOUN ')
    q41= input ('NOUN ')
    q42= input ('PLACE ')
    q43= input ('NUMBER ')
    print (f'I was {q33} along the sidewalk when an alien {q34} me. I was {q35} into their {q36} and it blasted off. Then the alien asked me to {q37} on the TV. I was suprised they spoke english. the aliens had a pet {q38}. We ordered a {q39} and it tasted good. As we came back into the galaxy, one alien asked me if I wanted a {q40}. I said no but I would like a {q41}. He got it for me and then dropped me off at my {q41}. then I realized I had been gone for {q42} years! ')
while q5== '5':
    q45= input ('VERB ')
    q46= input ('ADJECTIVE ')
    q47= input ('SILLY WORD	')
    q48 = input ('NUMBER ')
    q49 = input ('NOUN ')
    q50 = input ('ADJECTIVE ')
    q51 = input ('NOUN ')
    q52 = input ('OCCUPATION ')
    q53 = input ('AMOUNT OF TIME ')
    q54 = input ('VERB ')
    q55 = input ('PLACE ')
    q56 = input ('VERB ENDING IN "ED" ')
    q57 = input ('NOUN (PLURAL) ')
    q58 = input ('ADJECTIVE ')
    q59 = input ('VERB ENDING IN "ING" ')
    q60 = input ('VERB ')
    print (f'Good morning, Mr. Hunt. Your mission, should you choose to {q45} it, involves the recovery of a {q46} item designated "{q47}." You may select any {q48} {q49}, but it is {q50} that the third member of your {q49} be Nyah Nordoff-Hall. She is a {q50}, and a highly capable professional {q51}. You have {q52} to {q53} Miss Hall and meet me in {q54} to receive your assignment. As always, should any member of your {q49} be caught or {q55}, the {q56} will disavow all knowledge of your {q57}. And Mr. Hunt, the next time you go on holiday, please be {q58} enough to let us know where you`re {q59}. This message will self-{q60} in five seconds.')
while q5== '6':
    q62= input ('ADJECTIVE ')
    q63= input ('NOUN ')
    q64= input ('ANIMAL ')
    q65= input ('NOISE ')
    print (f'{q62} Macdonald had a {q63}, E-I-E-I-O and on that {q63} he had a {q64}, E-I-E-I-O with a {q65} {q65} here and a {q65} {q65} there, here a {q65}, there a {q65}, everywhere a {q65} {q65}, {q62} Macdonald had a {q63}, E-I-E-I-O.')
while q5 == '7':
    q67= input ('COLOR ')
    q68= input ('SUPERLATIVE (ENDING IS "EST") ')
    q69= input ('ADJECTIVE ')
    q70= input ('BODY PART (PLURAL) ')
    q71= input ('BODY PART ')
    q72= input ('NOUN ')
    q73= input ('ANIMAL (PLURAL) ')
    q74= input ('ADJECTIVE ')
    q75= input ('ADJECTIVE ')
    q76= input ('ADJECTIVE ')
    print (f'The {q67} Dragon is the {q68} Dragon of all. It has {q69} {q70}, and a/an {q71} shaped like a/an {q72}. It loves to eat {q73}, although it will feast on nearly anything. It is {q74} and {q75}. You must be {q76} around it, or you may end up as it`s meal!')
while q5== '8':
    q78= input ('VERB ')
    q79= input ('ADJECTIVE ')
    q80= input ('NOUN (PLURAL) ')
    q81= input ('ADJECTIVE ')
    q82= input ('VERB ENDING IN "ING" ')
    q83= input ('VERB ')
    q84= input ('NUMBER	')
    q85= input ('ADJECTIVE ')
    q86= input ('NOUN (PLURAL) ')
    q87= input ('NOUN (PLURAL) ')
    q88= input ('NOUN (PLURAL) ')
    q89= input ('RELATIVE (PLURAL) ')
    q90= input ('ADJECTIVE ')
    q91= input ('ADJECTIVE ')
    q92= input ('NOUN (PLURAL) ')
    print (f'Come {q78} at WALMART, where you`ll receive {q79} discounts on all of your favorite brand name {q80}. Our {q81} and {q82} associates are there to {q83} you {q84} hours a day. Here you will find {q85} prices on the {q86} you need. {q87} for the moms, {q88} for the kids and all the latest electronics for the {q89}. So come on down to your {q90} {q91} WALMART where the {q92} come first.')
while q5== '9':
    q94= input ('ADJECTIVE ')
    q95= input ('NOUN ')
    q96= input ('NOUN (PLURAL) ')
    q97= input ('NOUN ')
    q98= input ('VERB ENDING IN "ED" ')
    print (f'There was a/an {q94} woman who lived in a/an {q95}. She had so many {q96} she didn`t know what to do. She gave them some broth without any {q97}. She {q98} them all soundly and put them to bed.')
while q5== '10':
    q100= input ('NUMBER ')
    q101= input ('ADJECTIVE ')
    q102= input ('VERB ')
    q103= input ('OCCUPATION ')
    q104= input ('RELATION ')
    q105= input ('BODY PART (PLURAL) ')
    q106= input ('VERB ENDING IN "ING" ')
    q107= input ('NOUN ')
    print (f'{q100} {q101} mice! See how they {q102}! They all ran after the {q103}`s {q104}, Who cut off their {q105} with a {q106} knife. Did you ever see such a thing in your {q107} As {q100} {q101} mice?')