import colorama
from colorama import Fore, Back, Style
from colorama.initialise import init
colorama.init(autoreset=True)
q1= input ("Hello there! Welcome to Mad Libs! Press P to begin or Q to quit. ")
if q1 == ('q'):
    quit
while q1 == ('p'):
    print ('Select a topic:')
    print ('1. Greetings, Earthlings!')
    print ('2. Be Kind')
    print ('3. How To Wash Your Face')
    print ('4. Abducted by Aliens')
    print ('5. Popular Video Game')
    print ('6. Old Macdonald')
    print ('7. Drgons')
    print ('8. The WallMart Difference ')
    print ('9. There Was An Old Woman')
    print ('10. The Three Blind Mice')
    print ('11. Yankee Doodle')
    print ('12. The Cat And The Fiddle')
    print ('13. The New Day')
    q5= input ('Just write the number of the topic you want to play. ')
while q5 == '1':
    q6= input ('NOUN (PLURAL) ')
    q7= input ('OCCUPATION ')
    q8= input ('ANIMAL (PLURAL) ')
    q9= input ('PLACE ')
    q10= input ('VERB ')
    q11= input ('NOUN ')
    print (f'In the book War of the {Fore.BLUE}{q6}{Fore.RESET}, the main character is an anonymous {Fore.BLUE}{q7}{Fore.RESET} who records the arrival of {Fore.BLUE}{q8}{Fore.BLUE} in {Fore.BLUE}{q9}{Fore.RESET}. Needless to say, havoc reigns as the {Fore.BLUE}{q8}{Fore.RESET} continue to {Fore.BLUE}{q10}{Fore.reset} everything in sight, until they are killed by the common {Fore.BLUE}{q11}{Fore.RESET}.')
while q5 == '2':
    q12= input ("NOUN ")
    q13= input ("NOUN (PLURAL) ")
    q14= input ("NOUN ")
    q15= input ("PLACE ")
    q16= input ("ADJECTIVE ")
    q17= input ("NOUN ")
    print (f'Be kind to your {Fore.BLUE}{q12}{Fore.RESET}-footed {Fore.BLUE}{q13}{Fore.RESET} For a duck may be somebody`s {Fore.BLUE}{q14}{Fore.RESET}, Be kind to your {Fore.BLUE}{q14}{Fore.RESET} in {Fore.BLUE}{q15}{Fore.RESET} Where the weather is always {Fore.BLUE}{q16}{Fore.RESET}. You may think that this is the {Fore.BLUE}{q17}{Fore.RESET}, Well it is.')
while q5== '3':
    q18= input ('ADVERB	')
    q19= input ('NOUN ')
    q20= input ('LIQUID ')
    q21= input ('VERB ')
    q22= input ('NUMBER	')
    q23= input ('NOUN (PLURAL) ')
    q24= input ('VERB ')
    q25= input ('ADJECTIVE ')
    q26= input ('NOUN ')
    q27= input ('NOUN (PLURAL) ')
    q28= input ('ILLNESS ')
    q29= input ('OCCUPATION ')
    q30= input ('BODY PART (PLURAL) ')
    q31= input ('BODY PART ')
    print (f'In order to wash your face {Fore.BLUE}{q18}{Fore.RESET}, you must wet your {Fore.BLUE}{q19}{Fore.RESET} in warm {Fore.BLUE}{q20}{Fore.RESET}. Then, {Fore.BLUE}{q21}{Fore.RESET} it across your face {Fore.BLUE}{q22}{Fore.RESET} times. This will wash off any remainig {Fore.BLUE}{q23}{Fore.RESET}. When you are done you should {Fore.BLUE}{q24}{Fore.RESET} the cloth in {Fore.BLUE}{q25}{Fore.RESET} water to clean it. You should also wash your face with a {Fore.BLUE}{q26}{Fore.RESET} to keep it smooth and shiny. This will keep also keep away {Fore.BLUE}{q27}{Fore.RESET}. Don`t worry. It is normal to experience {Fore.BLUE}{q28}{Fore.RESET} the first time you try this. Consult your {Fore.BLUE}{q29}{Fore.RESET} if you break out in {Fore.BLUE}{q30}{Fore.RESET}. This works well on your {Fore.BLUE}{q31}{Fore.RESET} too!')
while q5== '4':
    q33= input ('VERB ENDING IN "ING" ')
    q34= input ('VERB ENDING IN "ED" ')
    q35= input ('VERB ENDING IN "ED" ')
    q36= input ('NOUN ')
    q37= input ('VERB ')
    q38= input ('ANIMAL ')
    q39= input ('NOUN ')
    q40= input ('NOUN ')
    q41= input ('NOUN ')
    q42= input ('PLACE ')
    q43= input ('NUMBER ')
    print (f'I was {Fore.BLUE}{q33}{Fore.RESET} along the sidewalk when an alien {Fore.BLUE}{q34}{Fore.RESET} me. I was {Fore.BLUE}{q35}{Fore.RESET} into their {Fore.BLUE}{q36}{Fore.RESET} and it blasted off. Then the alien asked me to {Fore.BLUE}{q37}{Fore.RESET} on the TV. I was suprised they spoke english. the aliens had a pet {Fore.BLUE}{q38}{Fore.RESET}. We ordered a {Fore.BLUE}{q39}{Fore.RESET} and it tasted good. As we came back into the galaxy, one alien asked me if I wanted a {Fore.BLUE}{q40}{Fore.RESET}. I said no but I would like a {Fore.BLUE}{q41}{Fore.RESET}. He got it for me and then dropped me off at my {Fore.BLUE}{q42}{Fore.RESET}. Then I realized I had been gone for {Fore.BLUE}{q43}{Fore.RESET} years! ')
while q5== '5':
    q45= input ('VERB ')
    q46= input ('ADJECTIVE ')
    q47= input ('SILLY WORD	')
    q48 = input ('NUMBER ')
    q49 = input ('NOUN ')
    q50 = input ('ADJECTIVE ')
    q51 = input ('NOUN ')
    q52 = input ('OCCUPATION ')
    q53 = input ('AMOUNT OF TIME ')
    q54 = input ('VERB ')
    q55 = input ('PLACE ')
    q56 = input ('VERB ENDING IN "ED" ')
    q57 = input ('NOUN (PLURAL) ')
    q58 = input ('ADJECTIVE ')
    q59 = input ('VERB ENDING IN "ING" ')
    q60 = input ('VERB ')
    print (f'Good morning, Mr. Hunt. Your mission, should you choose to {Fore.BLUE}{q45}{Fore.RESET} it, involves the recovery of a {Fore.BLUE}{q46}{Fore.RESET} item designated "{Fore.BLUE}{q47}{Fore.RESET}." You may select any {Fore.BLUE}{q48}{Fore.RESET} {Fore.BLUE}{q49}{Fore.RESET}, but it is {Fore.BLUE}{q50}{Fore.RESET} that the third member of your {Fore.BLUE}{q49}{Fore.RESET} be Nyah Nordoff-Hall. She is a {Fore.BLUE}{q50}{Fore.RESET}, and a highly capable professional {Fore.BLUE}{q51}{Fore.RESET}. You have {Fore.BLUE}{q52}{Fore.RESET} to {Fore.BLUE}{q53}{Fore.RESET} Miss Hall and meet me in {Fore.BLUE}{q54}{Fore.RESET} to receive your assignment. As always, should any member of your {Fore.BLUE}{q49}{Fore.RESET} be caught or {Fore.BLUE}{q55}{Fore.RESET}, the {Fore.BLUE}{q56}{Fore.RESET} will disavow all knowledge of your {Fore.BLUE}{q57}{Fore.RESET}. And Mr. Hunt, the next time you go on holiday, please be {Fore.BLUE}{q58}{Fore.RESET} enough to let us know where you`re {Fore.BLUE}{q59}{Fore.RESET}. This message will self-{Fore.BLUE}{q60}{Fore.RESET} in five seconds.')
while q5== '6':
    q62= input ('ADJECTIVE ')
    q63= input ('NOUN ')
    q64= input ('ANIMAL ')
    q65= input ('NOISE ')
    print (f'{Fore.BLUE}{q62}{Fore.RESET} Macdonald had a {Fore.BLUE}{q63}{Fore.RESET}, E-I-E-I-O and on that {Fore.BLUE}{q63}{Fore.RESET} he had a {Fore.BLUE}{q64}{Fore.RESET}, E-I-E-I-O with a {Fore.BLUE}{q65}{Fore.RESET} {Fore.BLUE}{q65}{Fore.RESET} here and a {Fore.BLUE}{q65}{Fore.RESET} {Fore.BLUE}{q65}{Fore.RESET} there, here a {Fore.BLUE}{q65}{Fore.RESET}, there a {Fore.BLUE}{q65}{Fore.RESET}, everywhere a {Fore.BLUE}{q65}{Fore.RESET} {Fore.BLUE}{q65}{Fore.RESET}, {Fore.BLUE}{q62}{Fore.RESET} Macdonald had a {Fore.BLUE}{q63}{Fore.RESET}, E-I-E-I-O.')
while q5 == '7':
    q67= input ('COLOR ')
    q68= input ('SUPERLATIVE (ENDING IS "EST") ')
    q69= input ('ADJECTIVE ')
    q70= input ('BODY PART (PLURAL) ')
    q71= input ('BODY PART ')
    q72= input ('NOUN ')
    q73= input ('ANIMAL (PLURAL) ')
    q74= input ('ADJECTIVE ')
    q75= input ('ADJECTIVE ')
    q76= input ('ADJECTIVE ')
    print (f'The {Fore.BLUE}{q67}{Fore.RESET} Dragon is the {Fore.BLUE}{q68}{Fore.RESET} Dragon of all. It has {Fore.BLUE}{q69}{Fore.RESET} {Fore.BLUE}{q70}{Fore.RESET}, and a/an {Fore.BLUE}{q71}{Fore.RESET} shaped like a/an {Fore.BLUE}{q72}{Fore.RESET}. It loves to eat {Fore.BLUE}{q73}{Fore.RESET}, although it will feast on nearly anything. It is {Fore.BLUE}{q74}{Fore.RESET} and {Fore.BLUE}{q75}{Fore.RESET}. You must be {Fore.BLUE}{q76}{Fore.RESET} around it, or you may end up as it`s meal!')
while q5== '8':
    q78= input ('VERB ')
    q79= input ('ADJECTIVE ')
    q80= input ('NOUN (PLURAL) ')
    q81= input ('ADJECTIVE ')
    q82= input ('VERB ENDING IN "ING" ')
    q83= input ('VERB ')
    q84= input ('NUMBER	')
    q85= input ('ADJECTIVE ')
    q86= input ('NOUN (PLURAL) ')
    q87= input ('NOUN (PLURAL) ')
    q88= input ('NOUN (PLURAL) ')
    q89= input ('RELATIVE (PLURAL) ')
    q90= input ('ADJECTIVE ')
    q91= input ('ADJECTIVE ')
    q92= input ('NOUN (PLURAL) ')
    print (f'Come {Fore.BLUE}{q78}{Fore.RESET} at WALMART, where you`ll receive {Fore.BLUE}{q79}{Fore.RESET} discounts on all of your favorite brand name {Fore.BLUE}{q80}{Fore.RESET}. Our {Fore.BLUE}{q81}{Fore.RESET} and {Fore.BLUE}{q82}{Fore.RESET} associates are there to {Fore.BLUE}{q83}{Fore.RESET} you {Fore.BLUE}{q84}{Fore.RESET} hours a day. Here you will find {Fore.BLUE}{q85}{Fore.RESET} prices on the {Fore.BLUE}{q86}{Fore.RESET} you need. {Fore.BLUE}{q87}{Fore.RESET} for the moms, {Fore.BLUE}{q88}{Fore.RESET} for the kids and all the latest electronics for the {Fore.BLUE}{q89}{Fore.RESET}. So come on down to your {Fore.BLUE}{q90}{Fore.RESET} {Fore.BLUE}{q91}{Fore.RESET} WALMART where the {Fore.BLUE}{q92}{Fore.RESET} come first.')
while q5== '9':
    q94= input ('ADJECTIVE ')
    q95= input ('NOUN ')
    q96= input ('NOUN (PLURAL) ')
    q97= input ('NOUN ')
    q98= input ('VERB ENDING IN "ED" ')
    print (f'There was a/an {Fore.BLUE}{q94}{Fore.RESET} woman who lived in a/an {Fore.BLUE}{q95}{Fore.RESET}. She had so many {Fore.BLUE}{q96}{Fore.RESET} she didn`t know what to do. She gave them some broth without any {Fore.BLUE}{q97}{Fore.RESET}. She {Fore.BLUE}{q98}{Fore.RESET} them all soundly and put them to bed.')
while q5== '10':
    q100= input ('NUMBER ')
    q101= input ('ADJECTIVE ')
    q102= input ('VERB ')
    q103= input ('OCCUPATION ')
    q104= input ('RELATION ')
    q105= input ('BODY PART (PLURAL) ')
    q106= input ('VERB ENDING IN "ING" ')
    q107= input ('NOUN ')
    print (f'{Fore.BLUE}{q100}{Fore.RESET} {Fore.BLUE}{q101}{Fore.RESET} mice! See how they {Fore.BLUE}{q102}{Fore.RESET}! They all ran after the {Fore.BLUE}{q103}{Fore.RESET}`s {Fore.BLUE}{q104}{Fore.RESET}, Who cut off their {Fore.BLUE}{q105}{Fore.RESET} with a {Fore.BLUE}{q106}{Fore.RESET} knife. Did you ever see such a thing in your {Fore.BLUE}{q107}{Fore.RESET} As {Fore.BLUE}{q100}{Fore.RESET} {Fore.BLUE}{q101}{Fore.RESET} mice?') 
while q5== '11':
    q109= input ('NOUN ')
    q110= input ('VERB ENDING IN "ING" ')
    q111= input ('ANIMAL ')
    q112= input ('ARTICLE OF CLOTHING ')
    q113= input ('NOUN (PLURAL) ')
    q114= input ('ADJECTIVE ')
    q115= input ('NOUN ')
    q116= input ('NOUN (PLURAL)	')
    print (f'Yankee Doodle went to {Fore.BLUE}{q109}{Fore.RESET}, a-{Fore.BLUE}{q110}{Fore.RESET} on a {Fore.BLUE}{q111}{Fore.RESET}; Stuck a feather in his {Fore.BLUE}{q112}{Fore.RESET} and called it {Fore.BLUE}{q113}{Fore.RESET}. Yankee Doodle keep it up, Yankee Doodle {Fore.BLUE}{q114}{Fore.RESET}, Mind the {Fore.BLUE}{q115}{Fore.RESET} and the step and with the {Fore.BLUE}{q116}{Fore.RESET} be handy.')
while q5== '12':
    q118= input ('SILLY WORD ')
    q119= input ('ANIMAL')
    q120= input ('MUSICAL INSTRUMENT ')
    q121= input ('NOUN ')
    q122= input ('ADJECTIVE ')
    q123= input ('NOUN ')
    print (f'Hey, {Fore.BLUE}{q118}{Fore.RESET}, {Fore.BLUE}{q118}{Fore.RESET}! The {Fore.BLUE}{q119}{Fore.RESET} and the {Fore.BLUE}{q120}{Fore.RESET}, The cow jumped over the {Fore.BLUE}{q121}{Fore.RESET}; The {Fore.BLUE}{q122}{Fore.RESET} dog laughed To see such sport, And the {Fore.BLUE}{q123}{Fore.RESET} ran away with the spoon.')
while q5== '13':
    q124= input ('VERB ENDING IN ING ')
    q125= input ('VERB ENDING IN ING ')
    q126= input ('VERB ENDING IN ED ')
    q127= input ('PLACE ')
    q128= input ('VERB ')
    q129= input ('VERB ')
    print (f'Tommorrow is a new day full of new suprises and new adventures. Such as {Fore.BLUE}{q124}{Fore.RESET} and {Fore.BLUE}{q125}{Fore.RESET}. Tommorrow leads you to the life you haven`t {Fore.BLUE}{q126}{Fore.RESET} yet. So why not plan to live today with the most adventurious and positive outlook because today is yesterday`s tommorrow and we all know that it`s good to do things differently. So let`s go to {Fore.BLUE}{q127}{Fore.RESET} and {Fore.BLUE}{q128}{Fore.RESET} with someone cool. Or you could just let it {Fore.BLUE}{q129}{Fore.RESET} right by.')